wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717859577
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 19
      - 23
      4: 3.11.4
      5: 0.17.1
      8:
      - 1
      - 4
      - 5
      10:
      - 9
      13: darwin-arm64
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
